#ifndef ESCDF_ATTRIBUTES_ID_H
#define ESCDF_ATTRIBUTES_ID_H

#define SYSTEM_NAME 0
#define NUMBER_OF_PHYSICAL_DIMENSIONS 1
#define DIMENSION_TYPE 2
#define EMBEDDED_SYSTEM 3
#define NUMBER_OF_SPECIES 4
#define NUMBER_OF_SITES 5
#define NUMBER_OF_SPECIES_AT_SITE 6
#define MAX_NUMBER_OF_SPECIES_AT_SITE 7
#define NUMBER_OF_SYMMETRY_OPERATIONS 8
#define LATTICE_VECTORS 9
#define SPACEGROUP_3D_NUMBER 10
#define SYMMORPHIC 11
#define TIME_REVERSAL_SYMMETRY 12

#endif
