#ifndef ESCDF_ATTRIBUTES_ID_H
#define ESCDF_ATTRIBUTES_ID_H

#define SYSTEM_NAME 0
#define NUMBER_OF_PHYSICAL_DIMENSIONS 1
#define DIMENSION_TYPE 2
#define EMBEDDED_SYSTEM 3
#define NUMBER_OF_SPECIES 4
#define NUMBER_OF_SITES 5
#define NUMBER_OF_SYMMETRY_OPERATIONS 6
#define LATTICE_VECTORS 7
#define SPACEGROUP_3D_NUMBER 8
#define SYMMORPHIC 9
#define TIME_REVERSAL_SYMMETRY 10

#endif
