/***********************************
 *       ID   specifications       *
 ***********************************

 This file is automatically generated. DO NOT EDIT! 
 In order to update the specifications, edit the file "attributes_def.json" 
 and run "python generate_attibutes_from_JSON.py". 
 */ 

#ifndef ESCDF_GROUPS_ID_H
#define ESCDF_GROUPS_ID_H

#define SYSTEM 0
#define DENSITY 1

#endif
